### ISSUE TITLE
Multiple file compile without error and without json

### ISSUE THREAD

**Issue by ojemuyiwa** [kenborge/grunt-angular-json#1]
Can't seem to compile multiple json files into one object. Wish I could post files but it stops after first two files and doesn't give an error. Issue is resolved when merge is set to false and files are separated into objects. "This is still very useable though"

**Comment by ojemuyiwa** [comment]
It loads only 2 files at a time and then degrades gracefully without any errors or messages. All json files have been parsed using https://jsonformatter.curiousconcept.com/

**Comment by kenjiqq** [comment]
Should be fixed now, i had read wrong how the merge library worked and thought it would merge more then one file at a time
